// Copyright (C) 2017  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel MegaCore Function License Agreement, or other 
// applicable license agreement, including, without limitation, 
// that your use is for the sole purpose of programming logic 
// devices manufactured by Intel and sold by Intel or its 
// authorized distributors.  Please refer to the applicable 
// agreement for further details.


// Generated by Quartus Prime Version 17.0 (Build Build 595 04/25/2017)
// Created on Mon May 03 14:34:45 2021

ADS805 ADS805_inst
(
	.CLK_SAMPLE(CLK_SAMPLE_sig) ,	// input  CLK_SAMPLE_sig
	.data_in(data_in_sig) ,	// input [11:0] data_in_sig
	.ADC_CLK(ADC_CLK_sig) ,	// output  ADC_CLK_sig
	.s_data_out(s_data_out_sig) ,	// output [11:0] s_data_out_sig
	.data_out(data_out_sig) 	// output [11:0] data_out_sig
);

