// Copyright (C) 2017  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel MegaCore Function License Agreement, or other 
// applicable license agreement, including, without limitation, 
// that your use is for the sole purpose of programming logic 
// devices manufactured by Intel and sold by Intel or its 
// authorized distributors.  Please refer to the applicable 
// agreement for further details.


// Generated by Quartus Prime Version 17.0 (Build Build 595 04/25/2017)
// Created on Sun May 02 14:09:40 2021

ChagBW ChagBW_inst
(
	.in(in_sig) ,	// input [IN_WIDTH-1:0] in_sig
	.out(out_sig) 	// output [OUT_WIDTH-1:0] out_sig
);

defparam ChagBW_inst.IN_WIDTH = 21;
defparam ChagBW_inst.DISCARD_WIDTH = 0;
defparam ChagBW_inst.OUT_WIDTH = 20;
